// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT4Q-ll90dnEw5ZnkqaoAie3KjTpiaVf0',
    appId: '1:20496632069:web:ebfbe64645af5a2ad1cf6c',
    messagingSenderId: '20496632069',
    projectId: 'delivery-67f06',
    authDomain: 'delivery-67f06.firebaseapp.com',
    storageBucket: 'delivery-67f06.appspot.com',
    measurementId: 'G-DV8KZHWGLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0VTfNMh9G9KbOj7QAosHKSqtRbDDj1mg',
    appId: '1:20496632069:android:6984f9bda2f114f5d1cf6c',
    messagingSenderId: '20496632069',
    projectId: 'delivery-67f06',
    storageBucket: 'delivery-67f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhA0vMI3Z2sf20IgGAY463qGHroBc1lFA',
    appId: '1:20496632069:ios:2bf74409a5d1dd48d1cf6c',
    messagingSenderId: '20496632069',
    projectId: 'delivery-67f06',
    storageBucket: 'delivery-67f06.appspot.com',
    iosBundleId: 'com.example.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhA0vMI3Z2sf20IgGAY463qGHroBc1lFA',
    appId: '1:20496632069:ios:2bf74409a5d1dd48d1cf6c',
    messagingSenderId: '20496632069',
    projectId: 'delivery-67f06',
    storageBucket: 'delivery-67f06.appspot.com',
    iosBundleId: 'com.example.rider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT4Q-ll90dnEw5ZnkqaoAie3KjTpiaVf0',
    appId: '1:20496632069:web:e883a504f3cdc00cd1cf6c',
    messagingSenderId: '20496632069',
    projectId: 'delivery-67f06',
    authDomain: 'delivery-67f06.firebaseapp.com',
    storageBucket: 'delivery-67f06.appspot.com',
    measurementId: 'G-BE2LKB6E8Y',
  );
}
